### ISSUE TITLE
IX_sample will not recognise list or array as 3-vector

### ISSUE THREAD

**Issue by davidvoneshen** [pace-neutrons/pace-python#37]
### Minimum code to reproduce issue

```python
from pace_neutrons import Matlab
import numpy as np
m = Matlab()

my_sample = m.IX_sample(True,[1,0,0],[0,1,0],'cuboid',[0.01,0.01,0.01])
```

in both jupyter and spyder on idaaas (with machine created today) gives the following error

```
HERBERT:IX_sample:invalid_argument: 'xgeom' must be a three-vector
```

I've also tried a numpy array rather than list and get the same issue.

**Comment by mducle** [comment]
Hi @davidvoneshen, sorry the syntax changed in Horace 4 with the first positional argument which is set to `True` here removed and replace by a keyword argument (`is_single_crystal`) which is set to `True` by default. So if you remove the first argument:

```python
my_sample = m.IX_sample([1,0,0],[0,1,0],'cuboid',[0.01,0.01,0.01])
```

it should work fine. Sorry I should have updated the documentation.

**Comment by davidvoneshen** [comment]
Yes that was indeed the issue. Please do update the docs appropriately.
